📝 adding content to about page
Doisaac/final-project-daw pull request #7
Opened 2024-05-14 04:02 UTC by Ricardo24Heredia

2024-05-14 05:44 UTC, Doisaac commented on css/style.css
> +    &::before {
We should delete this

2024-05-14 06:14 UTC, Doisaac commented on css/style.css
> +    &::before {
We could delete this pseudo-element

2024-05-14 06:20 UTC, Doisaac requested changes

2024-05-14 06:20 UTC, Doisaac commented on css/style.css
> +    &::before {
We could delete this pseudo-element

2024-05-14 06:22 UTC, Doisaac commented on css/style.css
> +    }
We could delete this unused pseudo-element

2024-05-14 06:24 UTC, Doisaac commented on css/style.css
> +      background-size: 100vw calc(100% + 400px);
We could delete this unused pseudo-element

2024-05-14 06:24 UTC, Doisaac commented on css/style.css
> +    &::before {
We could delete this unused pseudo-element

2024-05-14 06:25 UTC, Doisaac requested changes

2024-05-14 06:25 UTC, Doisaac commented on css/style.css
> +    }
We could delete this unused pseudo-element

2024-05-14 06:34 UTC, Doisaac approved these changes

2024-05-15 02:36 UTC, RNavarro23 approved these changes

2024-05-15 02:37 UTC, merged